#!/usr/bin/env python3
"""
================================================================================
IMPROVED & NEW VISUALS
================================================================================
Drop-in replacements and additions for generate_results.py.

IMPROVED FIGS (same function names — old versions commented inside):
  • fig2_mi_heatmap   — split-panel heatmap with marginal summary bars
  • fig3_attribution  — butterfly chart with per-combination swarm overlay
================================================================================
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.patches import FancyBboxPatch
import seaborn as sns
from scipy import stats
from typing import Dict
import os, logging

logger = logging.getLogger(__name__)

# ─── palette source of truth ────────────────────────────────────────────────
from generate_results import COLOR_SCHEME as COLORS
FIG_WIDTH_SINGLE = 3.5
FIG_WIDTH_DOUBLE = 7.0

# ============================================================================
# FIGURE/TABLE MAP (Improved Visuals)
# ----------------------------------------------------------------------------
# Figures generated by this module:
# - P1_fig2_mi_heatmap.pdf/.png        : fig2_mi_heatmap
# - P1_fig4_attribution.pdf/.png       : fig3_attribution
# - P1_fig_radar_agreement.pdf/.png    : fig_radar_estimator_agreement
# - P1_fig_pairwise_matrix.pdf/.png    : fig_pairwise_independence
#
# Tables generated by this module:
# - P1_table_per_combination_detail.csv/.tex
# - P1_table_estimator_diagnostics.csv/.tex
# ============================================================================


# ════════════════════════════════════════════════════════════════════════════
# HELPER: safe combo label
# ════════════════════════════════════════════════════════════════════════════
def _combo_label(combo: str) -> str:
    protected = {'L2-ARCTIC': 'L2__ARCTIC', 'UA-Speech': 'UA__Speech', 'MDVR-KCL': 'MDVR__KCL'}
    safe = combo
    for k, v in protected.items():
        safe = safe.replace(k, v)
    parts = [p.replace('__', '-').replace('_', ' ') for p in safe.split('-') if p]
    return ', '.join(parts)


def _short_combo(combo: str) -> str:
    """Very short 3-letter abbreviation per dataset."""
    protected = {'L2-ARCTIC': 'L2A', 'UA-Speech': 'UAS', 'MDVR-KCL': 'MKC',
                 'RAVDESS': 'RAV', 'IEMOCAP': 'IEM', 'GMU': 'GMU'}
    label = combo
    for full, abbr in protected.items():
        label = label.replace(full, abbr)
    parts = [p for p in label.split('-') if p]
    return '-'.join(parts[:3])


# ════════════════════════════════════════════════════════════════════════════
# IMPROVED: fig2_mi_heatmap  (split-panel with marginal bars)
# ════════════════════════════════════════════════════════════════════════════
# OLD VERSION: simple imshow heatmap with text annotations
# NEW VERSION: heatmap + right-side marginal mean bars + top-side per-pair means
#              + cleaner diverging colourmap + bold annotation for low-MI cells

def fig2_mi_heatmap(results, save_path):
    """Figure 2: Cross-dimension MI heatmap with marginal summary bars."""
    pairs = ['Emotion-Linguistic', 'Emotion-Pathology', 'Linguistic-Pathology', 'Source-Filter']
    pair_labels = ['Emo–Ling', 'Emo–Path', 'Ling–Path', 'Src–Flt']
    combos = list(results.keys())
    n_combos, n_pairs = len(combos), len(pairs)

    data = np.array([[results[c]['mi_results'].get(p, {}).get('combined_mean', np.nan)
                       for p in pairs] for c in combos])
    font_size = 9

    # ── Layout: heatmap + top bar + right bar ──
    fig = plt.figure(figsize=(FIG_WIDTH_SINGLE + 0.6, 0.32 * n_combos + 1.15))
    gs = gridspec.GridSpec(2, 2, width_ratios=[n_pairs, 1], height_ratios=[1, n_combos],
                           wspace=0.04, hspace=0.06)

    ax_heat = fig.add_subplot(gs[1, 0])
    # ax_top = fig.add_subplot(gs[0, 0], sharex=ax_heat)
    # ax_right = fig.add_subplot(gs[1, 1])
    ax_top = fig.add_subplot(gs[0, 0], sharex=ax_heat)
    ax_right = fig.add_subplot(gs[1, 1])
    ax_corner = fig.add_subplot(gs[0, 1])
    ax_corner.axis('off')

    vmax = max(1.0, np.nanmax(data))

    # ── Custom colourmap: white → green gradient (Final estimate theme) ──
    cmap = LinearSegmentedColormap.from_list(
        'mi_cmap', ['#F3FBF6', '#DDF2E4', '#BDE3CB', '#88C49D', '#1E8449'], N=256)
    norm = Normalize(vmin=0, vmax=vmax)

    # ── Main heatmap ──
    im = ax_heat.imshow(data, cmap=cmap, norm=norm, aspect='auto')
    for i in range(n_combos):
        for j in range(n_pairs):
            val = data[i, j]
            if np.isnan(val):
                continue
            txt_color = 'white' if val > vmax * 0.55 else '#333333'
            weight = 'bold' if val < 0.15 else 'normal'
            ax_heat.text(j, i, f'{val:.2f}', ha='center', va='center',
                         fontsize=font_size, color=txt_color, fontweight=weight)

    # ── Add thin grid lines between cells ──
    for x in np.arange(-0.5, n_pairs, 1):
        ax_heat.axvline(x, color='white', linewidth=0.5)
    for y in np.arange(-0.5, n_combos, 1):
        ax_heat.axhline(y, color='white', linewidth=0.5)

    ax_heat.set_xticks(range(n_pairs))
    ax_heat.set_xticklabels(pair_labels, fontsize=font_size, rotation=0, ha='center')
    ax_heat.set_yticks(range(n_combos))
    ax_heat.set_yticklabels([_combo_label(c) for c in combos], fontsize=font_size)
    ax_heat.set_xlabel('Dimension Pair', fontsize=font_size, fontweight='bold')
    ax_heat.set_ylabel('Dataset Combination', fontsize=font_size, fontweight='bold')
    ax_heat.tick_params(length=0)

    # ── Top marginal: per-pair mean ──
    col_means = np.nanmean(data, axis=0)
    x_centers = np.arange(n_pairs)
    hatch_styles = ['////', '\\\\\\\\', 'xxxx', '....']
    legend_labels = ['Emotion-Lingustic', 'Emotion-Pathology', 'Lingustic-Pathology', 'Source-Filter']
    legend_handles = []
    for j in range(n_pairs):
        ax_top.bar(x_centers[j], col_means[j], color='white', alpha=1.0,
                   edgecolor='black', linewidth=0.45, width=0.4, hatch=hatch_styles[j], align='center')
        legend_handles.append(
            mpatches.Patch(facecolor='white', edgecolor='black', hatch=hatch_styles[j], label=legend_labels[j])
        )
    mean_text_offset = 0.20
    for j, m in enumerate(col_means):
        ax_top.text(x_centers[j], m + mean_text_offset, f'{m:.2f}', ha='center', fontsize=font_size, fontweight='bold')
    ax_top.set_xlim(ax_heat.get_xlim())
    ax_top.set_ylim(0, max(vmax * 0.8, float(np.nanmax(col_means)) + mean_text_offset + 0.05))
    ax_top.set_xticks([])
    ax_top.set_ylabel('Mean', fontsize=font_size)
    ax_top.tick_params(labelsize=font_size, length=2)
    ax_top.spines['top'].set_visible(False)
    ax_top.spines['right'].set_visible(False)

    # ── Right marginal: per-combination mean ──
    # row_means = np.nanmean(data, axis=1)
    # ax_right.barh(range(n_combos), row_means, color='white', alpha=1.0,
    #               edgecolor='black', linewidth=0.45, height=0.7, hatch='////////')
    # for i, m in enumerate(row_means):
    #     ax_right.text(m + 0.01, i, f'{m:.2f}', va='center', fontsize=5.5)
    # ax_right.set_ylim(-0.5, n_combos - 0.5)
    # ax_right.set_xlim(0, vmax * 0.8)
    # ax_right.set_yticks([])
    # ax_right.set_xlabel('Mean', fontsize=7)
    # ax_right.tick_params(labelsize=6, length=2)
    # ax_right.invert_yaxis()
    # ax_right.spines['top'].set_visible(False)
    # ax_right.spines['right'].set_visible(False)
    ax_right.axis('off')

    plt.tight_layout(rect=[0, 0.02, 0.88, 1])

    # ── Colourbar (moved lower) ──
    cbar = fig.colorbar(im, ax=[ax_heat], shrink=0.9, pad=0.02, aspect=30)
    cbar.set_label('MI (nats)', fontsize=font_size)
    cbar.ax.tick_params(labelsize=font_size)
    cbar.ax.set_position([0.862, 0.07, 0.022, 0.375])

    # ── Legend stacked above colourbar (4 rows) ──
    fig.legend(handles=legend_handles, loc='center', bbox_to_anchor=(0.864, 0.67),
               ncol=1, fontsize=font_size, frameon=False, handlelength=1.6, labelspacing=0.35)

    heat_pos = ax_heat.get_position()
    top_pos = ax_top.get_position()
    ax_top.set_position([heat_pos.x0, top_pos.y0, heat_pos.width, top_pos.height])
    ax_top.set_xlim(ax_heat.get_xlim())

    plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()
    logger.info(f"  Saved: {save_path}")


# ════════════════════════════════════════════════════════════════════════════
# IMPROVED: fig3_attribution  (butterfly + swarm)
# ════════════════════════════════════════════════════════════════════════════
# OLD VERSION: simple diverging barh from 50% midpoint
# NEW VERSION: butterfly chart with source/filter stacked bars, per-combo
#              jitter points overlaid, 95% CI whiskers, and interpretation badges

def fig3_attribution(results, save_path):
    """Figure 3: Source-filter attribution butterfly chart with per-combo jitter."""
    dimensions = ['Emotional', 'Linguistic', 'Pathological']
    dim_colors = [COLORS['Emotional'], COLORS['Linguistic'], COLORS['Pathological']]
    font_size = 9

    # ── Aggregate per-combo source proportions ──
    attr_data = {d: [] for d in dimensions}
    for data in results.values():
        for dim in dimensions:
            if dim in data['attribution']:
                attr_data[dim].append(data['attribution'][dim]['source'])

    stats_data = {}
    for dim in dimensions:
        vals = attr_data[dim]
        if vals:
            m, s = np.mean(vals), np.std(vals)
            n = len(vals)
            ci = stats.t.ppf(0.975, df=max(n - 1, 1)) * s / np.sqrt(n) if n > 1 else 0
            stats_data[dim] = {'mean': m, 'std': s, 'ci': ci, 'n': n, 'vals': vals}

    if not stats_data:
        return

    fig, ax = plt.subplots(figsize=(FIG_WIDTH_SINGLE + 0.6, 2.8))
    y_pos = np.arange(len(dimensions))
    bar_h = 0.56

    for i, (dim, col) in enumerate(zip(dimensions, dim_colors)):
        if dim not in stats_data:
            continue
        sd = stats_data[dim]
        src_m = sd['mean']
        flt_m = 1 - src_m

        # ── Source bar (left of midpoint 0.5 → grows right) ──
        ax.barh(y_pos[i], src_m, height=bar_h, left=0, color=COLORS['Source'],
                alpha=0.88, edgecolor='#444', linewidth=0.5,
                label='Source (Glottal)' if i == 0 else None)
        # ── Filter bar (right portion) ──
        ax.barh(y_pos[i], flt_m, height=bar_h, left=src_m, color=COLORS['Filter'],
                alpha=0.88, edgecolor='#444', linewidth=0.5,
                label='Filter (Vocal Tract)' if i == 0 else None)

        # ── Per-combination jitter points ──
        jitter = np.random.default_rng(42).normal(0, 0.06, len(sd['vals']))
        ax.scatter(sd['vals'], y_pos[i] + jitter, s=12, color=col,
                   edgecolor='white', linewidth=0.3, zorder=5, alpha=0.8)

        # ── CI whisker on the source proportion ──
        ax.errorbar(src_m, y_pos[i], xerr=sd['ci'], fmt='|', color='black',
                    capsize=4, capthick=1.2, linewidth=1.2, zorder=6)

        # ── Labels ──
        label_y = y_pos[i] - (bar_h / 2 + 0.08)
        ax.text(src_m / 2, label_y, f'{src_m:.0%}', ha='center', va='bottom',
            fontsize=font_size * 0.5, fontweight='bold', color='black')
        ax.text(src_m + flt_m / 2, label_y, f'{flt_m:.0%}', ha='center', va='bottom',
            fontsize=font_size * 0.5, fontweight='bold', color='black')

        # ── Interpretation badge ──
        interp = 'Source-dom.' if src_m > 0.55 else ('Filter-dom.' if src_m < 0.45 else 'Balanced')
        badge_col = COLORS['Source'] if src_m > 0.55 else (COLORS['Filter'] if src_m < 0.45 else '#888')
        ax.annotate(interp, xy=(1.02, y_pos[i]), xycoords=('axes fraction', 'data'),
                    fontsize=font_size, color=badge_col, fontweight='bold', va='center')

    # ── 50% reference line ──
    ax.axvline(0.5, color='black', linestyle=':', linewidth=0.8, alpha=0.5, zorder=0)

    ax.set_xlim(0, 1)
    ax.set_ylim(-0.85, len(dimensions) - 0.5)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(['e', 'l', 'p'], fontsize=font_size, fontweight='bold', color='black')
    for tick_label in ax.get_yticklabels():
        tick_label.set_ha('center')
    ax.set_xlabel('Attribution Proportion', fontsize=font_size, fontweight='bold')
    ax.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
    ax.set_xticklabels(['0%', '25%', '50%', '75%', '100%'], fontsize=font_size)
    ax.invert_yaxis()

    # ── Legends (center-aligned): Row 1 source/filter; Row 2 per-dimension circles ──
    legend_row1 = ax.legend(
        handles=[
            mpatches.Patch(color=COLORS['Source'], label='Source (Glottal)'),
            mpatches.Patch(color=COLORS['Filter'], label='Filter (Vocal Tract)'),
        ],
        loc='upper center',
        bbox_to_anchor=(0.5, 1.45),
        ncol=2,
        fontsize=font_size,
        frameon=False,
        columnspacing=0.9,
        handletextpad=0.4,
    )
    legend_row1._legend_box.align = "center"

    legend_row2 = ax.legend(
        handles=[
            plt.Line2D([], [], marker='o', color=dim_colors[0], markerfacecolor=dim_colors[0],
                       markeredgecolor='white', markeredgewidth=0.3, markersize=5,
                       linestyle='', label='Emotional (e)'),
            plt.Line2D([], [], marker='o', color=dim_colors[1], markerfacecolor=dim_colors[1],
                       markeredgecolor='white', markeredgewidth=0.3, markersize=5,
                       linestyle='', label='Linguistic (l)'),
            plt.Line2D([], [], marker='o', color=dim_colors[2], markerfacecolor=dim_colors[2],
                       markeredgecolor='white', markeredgewidth=0.3, markersize=5,
                       linestyle='', label='Pathological (p)'),
        ],
        loc='upper center',
        bbox_to_anchor=(0.5, 1.30),
        ncol=3,
        fontsize=font_size,
        frameon=False,
        columnspacing=0.8,
        handletextpad=0.35,
    )
    legend_row2._legend_box.align = "center"
    ax.add_artist(legend_row1)

    plt.tight_layout(rect=[0, 0, 0.92, 0.72])
    plt.savefig(save_path, dpi=300, bbox_inches='tight', pad_inches=0.16, facecolor='white')
    plt.close()
    logger.info(f"  Saved: {save_path}")


# ════════════════════════════════════════════════════════════════════════════
# NEW FIGURE 1: Radar chart — estimator agreement per dimension pair
# ════════════════════════════════════════════════════════════════════════════

def fig_radar_estimator_agreement(results, save_path):
    """
    Radar chart showing how tightly MINE, CLUB, and KSG agree for each pair.
    Each spoke = a dimension pair; each polygon = an estimator.
    Reveals at a glance where bounds are tight vs. divergent.
    """
    pairs = ['Emotion-Linguistic', 'Emotion-Pathology', 'Linguistic-Pathology', 'Source-Filter']
    pair_labels = ['Emo–Ling', 'Emo–Path', 'Ling–Path', 'Src–Flt']
    estimators = [('mine_mean', 'MINE', COLORS['MINE']),
                  ('club_mean', 'CLUB', COLORS['CLUB']),
                  ('ksg_mean',  'KSG',  COLORS['KSG']),
                  ('combined_mean', 'Final', COLORS['Final'])]

    # ── Aggregate means ──
    agg = {p: {} for p in pairs}
    for p in pairs:
        for key, _, _ in estimators:
            vals = [d['mi_results'][p][key] for d in results.values() if p in d['mi_results']]
            agg[p][key] = np.mean(vals) if vals else 0.0

    n_spokes = len(pairs)
    angles = np.linspace(0, 2 * np.pi, n_spokes, endpoint=False).tolist()
    angles += angles[:1]  # close polygon

    fig, ax = plt.subplots(figsize=(FIG_WIDTH_SINGLE + 0.3, FIG_WIDTH_SINGLE + 0.3),
                           subplot_kw=dict(polar=True))

    vmax = max(agg[p][k] for p in pairs for k, _, _ in estimators) * 1.25

    for key, label, color in estimators:
        values = [agg[p][key] for p in pairs]
        values += values[:1]
        lw = 2.0 if label == 'Final' else 1.2
        ls = '-' if label == 'Final' else '--'
        ax.plot(angles, values, color=color, linewidth=lw, linestyle=ls, label=label)
        ax.fill(angles, values, color=color, alpha=0.06)

    # ── Spoke labels ──
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(pair_labels, fontsize=8, fontweight='bold')
    ax.set_ylim(0, vmax)
    ax.set_yticks(np.arange(0, vmax, 0.2))
    ax.set_yticklabels([f'{v:.1f}' for v in np.arange(0, vmax, 0.2)], fontsize=6, color='grey')
    ax.yaxis.set_label_position('left')

    # ── Independence threshold ring ──
    threshold = 0.15
    theta_ring = np.linspace(0, 2 * np.pi, 100)
    ax.plot(theta_ring, [threshold] * 100, color=COLORS['Threshold'],
            linestyle=':', linewidth=1.5, alpha=0.7, label='Independence\nthreshold (0.15)')

    ax.legend(loc='center left', bbox_to_anchor=(1.18, 0.5), ncol=1,
              fontsize=6.8, frameon=False, borderaxespad=0.3)
    ax.set_title('Estimator Agreement\nAcross Dimension Pairs', fontsize=10,
                 fontweight='bold', pad=20)

    plt.tight_layout(rect=[0, 0, 0.82, 1])
    plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()
    logger.info(f"  Saved: {save_path}")


# ════════════════════════════════════════════════════════════════════════════
# NEW FIGURE 2: Pairwise independence matrix with effect-size annotation
# ════════════════════════════════════════════════════════════════════════════

def fig_pairwise_independence(results, save_path):
    """
    Symmetric 5×5 matrix of all feature-set pairs (s, f, e, l, p) showing MI
    in the lower triangle and a qualitative independence badge in the upper.
    Inspired by NeurIPS correlation-matrix figures.
    """
    feature_keys = ['source', 'filter', 'emotional', 'linguistic', 'pathological']
    labels = ['Source', 'Filter', 'Emotional', 'Linguistic', 'Pathological']
    short = ['s', 'f', 'e', 'l', 'p']
    n = len(labels)

    from itertools import combinations

    # ── Compute KSG MI for all 10 unique pairs, averaged across combos ──
    from scipy.special import digamma
    from scipy.spatial import cKDTree

    class _KSG:
        def __init__(self, k=5):
            self.k = k
        def estimate(self, x, y):
            nn = x.shape[0]
            if nn < self.k + 1: return 0.0
            x = (x - x.mean(0)) / (x.std(0) + 1e-10)
            y = (y - y.mean(0)) / (y.std(0) + 1e-10)
            xy = np.hstack([x, y])
            tree_xy = cKDTree(xy); tree_x = cKDTree(x); tree_y = cKDTree(y)
            d, _ = tree_xy.query(xy, k=self.k+1, p=np.inf)
            eps = d[:, -1]
            nx = np.array([len(tree_x.query_ball_point(x[i], eps[i]-1e-10, p=np.inf))-1 for i in range(nn)])
            ny = np.array([len(tree_y.query_ball_point(y[i], eps[i]-1e-10, p=np.inf))-1 for i in range(nn)])
            nx, ny = np.maximum(nx, 1), np.maximum(ny, 1)
            return max(0.0, digamma(self.k)+digamma(nn)-np.mean(digamma(nx+1)+digamma(ny+1)))

    ksg = _KSG(k=5)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()

    mi_matrix = np.full((n, n), np.nan)
    for ci, cj in combinations(range(n), 2):
        vals = []
        for combo_data in results.values():
            feats = combo_data['features']
            x = feats.get(feature_keys[ci])
            y = feats.get(feature_keys[cj])
            if x is not None and y is not None:
                nn = min(len(x), len(y))
                xn = scaler.fit_transform(x[:nn])
                yn = scaler.fit_transform(y[:nn])
                vals.append(ksg.estimate(xn, yn))
        if vals:
            mi_matrix[ci, cj] = np.mean(vals)
            mi_matrix[cj, ci] = np.mean(vals)
    np.fill_diagonal(mi_matrix, np.nan)

    # ── Plot ──
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_SINGLE + 0.8, FIG_WIDTH_SINGLE + 0.5))

    cmap = LinearSegmentedColormap.from_list('indep', ['#E8F5E9', '#FFECB3', '#FFCDD2'], N=256)
    vmax = max(1.0, np.nanmax(mi_matrix))
    masked = np.ma.masked_invalid(mi_matrix)

    im = ax.imshow(masked, cmap=cmap, vmin=0, vmax=vmax, aspect='equal')

    # ── Annotations: lower triangle = MI value, upper triangle = badge ──
    for i in range(n):
        for j in range(n):
            if i == j:
                ax.text(j, i, f'{short[i]}', ha='center', va='center',
                        fontsize=11, fontweight='bold', color='#333', style='italic')
            elif i > j:  # lower triangle → MI value
                val = mi_matrix[i, j]
                if not np.isnan(val):
                    ax.text(j, i, f'{val:.2f}', ha='center', va='center', fontsize=8,
                            fontweight='bold', color='#333')
            else:  # upper triangle → badge
                val = mi_matrix[i, j]
                if not np.isnan(val):
                    if val < 0.15:
                        badge, bcol = '✓ Indep.', '#2E7D32'
                    elif val < 0.5:
                        badge, bcol = '~ Weak', '#F57F17'
                    else:
                        badge, bcol = '✗ Coupled', '#C62828'
                    ax.text(j, i, badge, ha='center', va='center',
                            fontsize=6.5, fontweight='bold', color=bcol)

    # ── Grid ──
    for x in np.arange(-0.5, n, 1):
        ax.axvline(x, color='white', linewidth=1.5)
        ax.axhline(x, color='white', linewidth=1.5)

    ax.set_xticks(range(n))
    ax.set_xticklabels(labels, fontsize=8, fontweight='bold')
    ax.set_yticks(range(n))
    ax.set_yticklabels(labels, fontsize=8, fontweight='bold')
    ax.tick_params(length=0)

    cbar = fig.colorbar(im, ax=ax, shrink=0.7, pad=0.04)
    cbar.set_label('MI (nats)', fontsize=8)
    cbar.ax.tick_params(labelsize=6)

    ax.set_title('Pairwise Feature-Set Independence', fontsize=10, fontweight='bold', pad=10)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()
    logger.info(f"  Saved: {save_path}")


# ════════════════════════════════════════════════════════════════════════════
# NEW TABLE 1: Per-combination MI detail
# ════════════════════════════════════════════════════════════════════════════

def table_per_combination_detail(results, output_dir):
    """
    Detailed per-combination table: each combo × pair → MINE, CLUB, Final, Δ.
    Useful for supplementary material or reviewer response.
    """
    pairs = ['Emotion-Linguistic', 'Emotion-Pathology', 'Linguistic-Pathology', 'Source-Filter']
    rows = []
    for combo, data in results.items():
        for p in pairs:
            mi = data['mi_results'].get(p)
            if mi is None:
                continue
            rows.append({
                'Combination': _combo_label(combo),
                'Pair': p,
                'MINE': f"{mi['mine_mean']:.3f}",
                'CLUB': f"{mi['club_mean']:.3f}",
                'KSG': f"{mi['ksg_mean']:.3f}",
                'Final': f"{mi['combined_mean']:.3f}",
                'Δ': f"{mi['uncertainty']:.3f}",
                'Converged': f"{mi.get('n_converged', '—')}/{len(mi.get('convergence', []))}",
            })

    df = pd.DataFrame(rows)
    csv_path = os.path.join(output_dir, 'P1_table_per_combination.csv')
    df.to_csv(csv_path, index=False)

    # ── LaTeX ──
    latex = r"""\begin{table*}[t]
\centering
\caption{Per-combination MI estimates across all dimension pairs (nats). $\Delta$ = CLUB $-$ MINE. Conv.\ = converged ensemble members / total.}
\label{tab:per_combo}
\resizebox{\textwidth}{!}{%
\begin{tabular}{llcccccl}
\toprule
\textbf{Dataset Combination} & \textbf{Dimension Pair} & \textbf{MINE} & \textbf{CLUB} & \textbf{KSG} & \textbf{Final} & $\boldsymbol{\Delta}$ & \textbf{Conv.} \\
\midrule
"""
    prev_combo = None
    for _, row in df.iterrows():
        combo_cell = row['Combination'] if row['Combination'] != prev_combo else ''
        prev_combo = row['Combination']
        pair_fmt = row['Pair'].replace('-', '--')
        final_fmt = f"\\textbf{{{row['Final']}}}"
        delta_fmt = row['Δ']
        latex += f"{combo_cell} & {pair_fmt} & {row['MINE']} & {row['CLUB']} & {row['KSG']} & {final_fmt} & {delta_fmt} & {row['Converged']} \\\\\n"

    latex += r"""\bottomrule
\end{tabular}}
\end{table*}
"""
    tex_path = os.path.join(output_dir, 'P1_table_per_combination.tex')
    with open(tex_path, 'w') as f:
        f.write(latex)

    logger.info(f"  Saved: {csv_path}")
    logger.info(f"  Saved: {tex_path}")
    return df


# ════════════════════════════════════════════════════════════════════════════
# NEW TABLE 2: Estimator diagnostics
# ════════════════════════════════════════════════════════════════════════════

def table_estimator_diagnostics(results, output_dir):
    """
    Diagnostic table: per dimension pair, reports estimator-level statistics
    including convergence rate, KSG weight used, MINE–KSG deviation,
    CLUB–KSG deviation, and bound tightness ratio.
    """
    pairs = ['Emotion-Linguistic', 'Emotion-Pathology', 'Linguistic-Pathology', 'Source-Filter']
    rows = []

    for p in pairs:
        mine_vals, club_vals, ksg_vals, final_vals, conv_rates = [], [], [], [], []
        for data in results.values():
            mi = data['mi_results'].get(p)
            if mi is None:
                continue
            mine_vals.append(mi['mine_mean'])
            club_vals.append(mi['club_mean'])
            ksg_vals.append(mi['ksg_mean'])
            final_vals.append(mi['combined_mean'])
            n_conv = mi.get('n_converged', 0)
            n_total = len(mi.get('convergence', []))
            conv_rates.append(n_conv / n_total if n_total > 0 else 0)

        if not mine_vals:
            continue

        mine_m, club_m, ksg_m = np.mean(mine_vals), np.mean(club_vals), np.mean(ksg_vals)
        delta = club_m - mine_m
        # KSG weight: from adaptive weighting formula
        w_ksg = min(0.6, 0.3 + delta * 0.1) if delta > 1.0 else 0.3
        # Bound tightness: ratio of gap to final estimate
        final_m = np.mean(final_vals)
        tightness = delta / final_m if final_m > 0.01 else float('inf')

        rows.append({
            'Pair': p,
            'MINE (mean)': f"{mine_m:.3f}",
            'CLUB (mean)': f"{club_m:.3f}",
            'KSG (mean)': f"{ksg_m:.3f}",
            'Δ (gap)': f"{delta:.3f}",
            'w_KSG': f"{w_ksg:.2f}",
            '|MINE−KSG|': f"{abs(mine_m - ksg_m):.3f}",
            '|CLUB−KSG|': f"{abs(club_m - ksg_m):.3f}",
            'Tightness (Δ/Final)': f"{tightness:.2f}" if tightness < 100 else '—',
            'Conv. rate': f"{np.mean(conv_rates):.0%}",
        })

    df = pd.DataFrame(rows)
    csv_path = os.path.join(output_dir, 'P1_table_estimator_diagnostics.csv')
    df.to_csv(csv_path, index=False)

    # ── LaTeX ──
    latex = r"""\begin{table}[t]
\centering
\caption{Estimator diagnostics: convergence, adaptive weighting, and bound agreement. $w_\text{KSG}$ = KSG anchor weight in Eq.~(11). Tightness = $\Delta / \hat{I}_\text{final}$ (lower is better).}
\label{tab:diagnostics}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{lccccccc}
\toprule
\textbf{Pair} & $\boldsymbol{\Delta}$ & $\boldsymbol{w_\text{KSG}}$ & $|\text{MINE}{-}\text{KSG}|$ & $|\text{CLUB}{-}\text{KSG}|$ & \textbf{Tightness} & \textbf{Conv.\ rate} \\
\midrule
"""
    for _, row in df.iterrows():
        pair_fmt = row['Pair'].replace('-', '--')
        latex += (f"{pair_fmt} & {row['Δ (gap)']} & {row['w_KSG']} & "
                  f"{row['|MINE−KSG|']} & {row['|CLUB−KSG|']} & "
                  f"{row['Tightness (Δ/Final)']} & {row['Conv. rate']} \\\\\n")

    latex += r"""\bottomrule
\end{tabular}}
\end{table}
"""
    tex_path = os.path.join(output_dir, 'P1_table_estimator_diagnostics.tex')
    with open(tex_path, 'w') as f:
        f.write(latex)

    logger.info(f"  Saved: {csv_path}")
    logger.info(f"  Saved: {tex_path}")
    return df


# ════════════════════════════════════════════════════════════════════════════
# INTEGRATION HELPER
# ════════════════════════════════════════════════════════════════════════════

def generate_all_improved_and_new(results, figures_dir, tables_dir):
    """
    Call this from main() after the existing generate calls.
    Generates all improved + new visuals.
    """
    # Improved (same names — will overwrite originals)
    fig2_mi_heatmap(results, os.path.join(figures_dir, 'P1_fig2_mi_heatmap.pdf'))
    fig2_mi_heatmap(results, os.path.join(figures_dir, 'P1_fig2_mi_heatmap.png'))
    fig3_attribution(results, os.path.join(figures_dir, 'P1_fig4_attribution.pdf'))
    fig3_attribution(results, os.path.join(figures_dir, 'P1_fig4_attribution.png'))

    # New figures
    # fig_radar_estimator_agreement(results, os.path.join(figures_dir, 'P1_fig_radar_agreement.pdf'))
    # fig_radar_estimator_agreement(results, os.path.join(figures_dir, 'P1_fig_radar_agreement.png'))
    # fig_pairwise_independence(results, os.path.join(figures_dir, 'P1_fig_pairwise_matrix.pdf'))
    # fig_pairwise_independence(results, os.path.join(figures_dir, 'P1_fig_pairwise_matrix.png'))

    # New tables (commented out)
    # table_per_combination_detail(results, tables_dir)
    # table_estimator_diagnostics(results, tables_dir)


if __name__ == '__main__':
    print("This module is meant to be imported by generate_results.py")
    print("Add to main():  from improved_visuals import generate_all_improved_and_new")
    print("                 generate_all_improved_and_new(improved, figures_dir, tables_dir)")
